### ISSUE TITLE
Fix slack to discord urls breaking

### ISSUE THREAD

**Issue by Jakousa** [UniversityOfHelsinkiCS/toska-silta#20]
Happens sometimes, no repro idea. Might have something to do with an embed? There might be a regex solution to check every message and remove if this happens.

(Btw embeds are not passed to the other side. Maybe they should? Is it possible?)

![image](https://user-images.githubusercontent.com/6400208/135993750-d01a1f1c-5ef6-485d-9417-2d08d3f2d865.png)

**Comment by ZeroDayOwl** [comment]
If the URLs work fine, Discord should be able to generate the embeds there. So even if it is possible, I think passing embeds would be redundant.

**Comment by ZeroDayOwl** [comment]
Also @Jakousa, your URL is being pipe-lined through itself, because http://yle.fi/uutiset/3-12125116%7Chttp://yle.fi/uutiset/3-12125116 is the same as http://yle.fi/uutiset/3-12125116|http://yle.fi/uutiset/3-12125116.

![image](https://user-images.githubusercontent.com/56065602/135996447-b84dfc89-8539-409c-88a3-bfe2ca8755f6.png)

I think it might have something to do with the embed. The API gets the messages, and since there's an embed after the URL, it might have been placing the embed's URL (which is the same as the original one) after the original URL with a pipeline.

**Comment by sasumaki** [comment]
I maybe fixed it https://github.com/UniversityOfHelsinkiCS/toska-silta/commit/e55e20202402d669b9ae649fe70d9f23d6fa37bc
Thanks @LoneRanger1337!

**Comment by ZeroDayOwl** [comment]
No worries @sasumaki !

**Comment by Rochet2** [comment]
Issue still persists. Example `http://ledbaseline.com/%7CLedbaseline.com`
Seems that the current regex in https://github.com/UniversityOfHelsinkiCS/toska-silta/commit/e55e20202402d669b9ae649fe70d9f23d6fa37bc is not matching because the latter part of the URL does not have `http://` at the beginning of it.
Making `http://` optional in the regex might fix the issue.

On a quick look the code in https://github.com/UniversityOfHelsinkiCS/toska-silta/commit/e55e20202402d669b9ae649fe70d9f23d6fa37bc looked to me like it erases the entire link (replaces with empty string) resulting in no link at all, so I did not commit a fix yet. Should probably test it before committing.

**Comment by Rochet2** [comment]
This should now be fixed in https://github.com/UniversityOfHelsinkiCS/toska-silta/commit/5496a9ac92e5c3718e6cfc973bc1e07b28bb3fc1

The links in the messages are originally in the following format: `<http://google.com/|google.com>`
The latter part is what a user actually wrote in chat and the former part is a deduced link.
I opted to remove everything else except the actual text written by a user, leaving `google.com`.
